module.exports.descriptors = [
    'Aloha Petroleum',
    'Alon',
    'American Gas',
    'Amoco',
    'ARCO',
    'Billups',
    'BP',
    'Buc-ees',
    'Caseys General Stores',
    'CEFCO',
    'CENEX',
    'Chevron',
    'Circle K',
    'Citgo',
    'Clark Brands',
    'Conoco',
    'Costco brand gasoline',
    'Crown',
    'Cumberland Farms',
    'Delta Sonic',
    'Exxon',
    'Etna',
    'Family Express',
    'Fastrac',
    'Fastrip',
    'Frontier',
    'Flying J',
    'Gant',
    'GasAmerica',
    'Gas City, Ltd',
    'GasTrac',
    'Sams Club',
    'Safeway',
    'Servco',
    'Sheetz',
    'Shell',
    'Valero',
]

module.exports.places = [
    'Flats',
    'Village',
    'Canyon',
    'Pond',
    'Group Station',
    'Horse Station',
    'Ghost Town',
    'Station',
    'Dispersed Station',
    'Backcountry',
    'River',
    'Creek',
    'Creekside',
    'Bay',
    'Spring',
    'Bayshore',
    'Sands',
    'Mule Station',
    'Hunting Station',
    'Cliffs',
    'Hollow'
]